### ISSUE TITLE
Restrição de transição

### ISSUE THREAD

**Issue by caahreginaa** [RafaelRSPX/AllPetri#10]
Pessoal, como acredito que não possa existir uma transição de um lugar para ele mesmo, acredito que deveríamos acrescentar essa restrição no código.

**Comment by RafaelRSPX** [comment]
Sim, concordo. Afinal, não haveria trabalho se uma transição fosse para o mesmo lugar.

**Comment by flavioduart** [comment]
Também concordo, e simplificaria.

**Comment by eilins** [comment]
Ficaria muito legal!

**Comment by RafaelRSPX** [comment]
Implementado no seguinte commit: b28666bff00cc88ec47e0094ca0f906183d56df1
