### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by flavioduart** [RafaelRSPX/AllPetri#11]
Galerinha, tava conversando com Cássia hoje, e achamos melhor deixar pra colocar os comentários só quando o final estiver pronto, porque se for adicionar algum comentário em cima de algum que já tiver, todo o meio entre os dois vira comentário e isso faz perder tempo. :imp:

**Comment by eilins** [comment]
Testei agora isso e realmente, fica chato, e concordo pra deixar pro fim do programa. Vou excluir.

**Comment by eilins** [comment]
Pronto, retirado todos.
