### ISSUE TITLE
Valores

### ISSUE THREAD

**Issue by flavioduart** [RafaelRSPX/AllPetri#12]
Galera, no exemplo que o professor deu na sala de aula, ele começa com o valor 0, por exemplo, "lugar 0", "arco 0", e o nosso programa começa com o valor 1. Digam a opinião de vocês, se preferem mudar pra 0 ou deixar como está.

**Comment by caahreginaa** [comment]
Por mim tanto faz.

**Comment by RafaelRSPX** [comment]
A transição começa a partir de 1 ou 0?

**Comment by caahreginaa** [comment]
No momento, no códgio ta imprimindo a partir de 1, mas podemos colocar 0.

**Comment by caahreginaa** [comment]
Coloquei pra 0.

**Comment by RafaelRSPX** [comment]
Tava bom a partir do 1. Eu adicionar o arquivo entrada-exemplo1.txt baseado na contagem a partir do 1. Mas já que alterasse, vou alterar o arquivo de entrada.
