### ISSUE TITLE
Matriz de Transição 

### ISSUE THREAD

**Issue by eilins** [RafaelRSPX/AllPetri#13]
A matriz de transição atual não ta sendo usada. Vai usa-la de outra forma ou devemos apagar?

**Comment by caahreginaa** [comment]
Por mim, nós podemos apagar. Se for o caso de usarmos uma matriz pra alguma outra coisa, fazemos outra.

**Comment by RafaelRSPX** [comment]
Ainda não sei como utilizar a matriz de transição, mas na parte do processamento, vamos precisar da direção da transição, os arcos que envolvem a transição e o custo dos arcos.

**Comment by caahreginaa** [comment]
Apaguei a matriz porque tava inútil no código. Mas a maior parte dos valores que usaremos estão salvos como vetores, podemos então "corresponder" a posição do vetor em que está a variável que queremos.
