### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/AllPetri#14]
Vamos supor que eu tenho uma rede simples:
2 lugares,
2 transições e
4 arcos.

Deste jeito:
![image](https://cloud.githubusercontent.com/assets/13755711/13900713/a94e590c-edeb-11e5-8085-497451b35a26.png)

Suponha que o o token ativou a T0 e produziu o token no L1.

O resultado vai ser um token no em ambos os lugares, mantendo o token no lugar L0:
![image](https://cloud.githubusercontent.com/assets/13755711/13900732/40d700f8-edec-11e5-9692-bc5d2d901b02.png)

Ou o token no lugar L0 é gasto e o lugar L0 fica sem token?
![image](https://cloud.githubusercontent.com/assets/13755711/13900737/5e8afc58-edec-11e5-8010-981298ee7fd7.png)

**Comment by caahreginaa** [comment]
Acredito que a segunda imagem, pois esse arco em direção a transição precisa "cobrar" uma certa quantidade de tokens para "enviar" outra quantidade para outro lugar.

**Comment by RafaelRSPX** [comment]
Também achei que seria o segundo resultado.

**Comment by RafaelRSPX** [comment]
O exemplo desta issue aqui representa a entrada de dados do teste-exemplo1.txt do commit: f3fe0ca3af57d76e5ecb092615a1e57d893140b3
