### ISSUE TITLE
Trasição

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/AllPetri#15]
A primeira transição é T0 ou T1? Ou seja, a contagem começa do 0 ou de 1?

**Comment by caahreginaa** [comment]
Tem uma issue sobre isso. No momento, começa sempre do 1, mas estamos discutindo pra saber se deveriamos colocar 0.

**Comment by RafaelRSPX** [comment]
Ok. Desde que tudo esteja padronizado
