### ISSUE TITLE
Erro ao mostrar valor 

### ISSUE THREAD

**Issue by eilins** [RafaelRSPX/AllPetri#16]
Ao rodar o programa, na parte do "Quantos tokens possui o lugar tal?" sempre fica o numero 1 na frente. Por exemplo, se botar que existem 5 lugares, na pergunta ficará: Quantos tokens possui o lugar 10? Quantos tokens possui o lugar 11? E assim por diante.

**Comment by flavioduart** [comment]
Vinicius, eu rodei o programa agora e reparei isso também; e não só aí, na pergunta "Quantos arcos saem do lugar tal?" também acontece isso, mas irei ajeitar!

**Comment by flavioduart** [comment]
Pronto, corrigido! :+1:

**Comment by flavioduart** [comment]
Reparei que não era "1" e sim "l" indicando lugar, mas (re)corrigi e melhores para ficar melhor a visualização disso :dancer:
