### ISSUE TITLE
Disparo da transição

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/AllPetri#17]
Para que uma transição seja disparada todos os arcos que vão para uma transição devem ser disparados, correto? Se isso for verdade, talvez seja necessário verificar quantos arcos vão para cada transição. Verificar se todos os arcos dispararam para depois disparar a transição.

**Comment by wesleysilas** [comment]
Acho que não necessariamente todos os arcos têm que disparar.
Se um dos arcos estiver inativo, não dispara, mas se outro paralelo estiver, chega à transiçao sim.
A não ser que tenha apenas um arco indo para cada transição;

**Comment by caahreginaa** [comment]
Acho que só um arco precisa disparar. Pelo que eu entendi de disparo da transição, ela "dispara" quando é utilizada, então se qualquer um dos arcos a utilizarem, ela disparou.

**Comment by RafaelRSPX** [comment]
Então, se uma transição tem dois arcos direcionados para ela, ela só precisa de apenas um desses arcos para ser ativado. Certo?

**Comment by caahreginaa** [comment]
Exatamente.

**Comment by RafaelRSPX** [comment]
Ok. Então, acredito que isso facilite as coisas.
