### ISSUE TITLE
Autores.

### ISSUE THREAD

**Issue by flavioduart** [RafaelRSPX/AllPetri#2]
Fiz o documento dos AUTHORS. Seria bom cada um olhar e ver se ta tudo certo com sua informação. Quando ver comentar "ok", e o ultimo a ver fechar a issue! (Caso haja erro, só alterar)

**Comment by caahreginaa** [comment]
O meu também esta ok.

**Comment by eilins** [comment]
Tudo certo no meu!!

**Comment by wesleysilas** [comment]
o meu ta td certo tbm!
