### ISSUE TITLE
Variáveis 

### ISSUE THREAD

**Issue by caahreginaa** [RafaelRSPX/AllPetri#4]
Pessoal, acredito que seria viável usarmos struct pra armazenar algumas variáveis, pois assim será mais fácil passá-las de função para função.

**Comment by RafaelRSPX** [comment]
Exatamente. Também acho viável

**Comment by flavioduart** [comment]
Eu também acho legal, Cássia.

**Comment by caahreginaa** [comment]
Foi implementado.
