### ISSUE TITLE
Transição

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/AllPetri#5]
Os lugares são vetores de inteiros, mas a transição de um lugar para outro seria uma matriz, já que podemos direcionar? Por exemplo: um token ir para o lugar 2 para o lugar 1, utilizaríamos uma matriz transicao[2][1]?

**Comment by flavioduart** [comment]
Eu acredito que usaria matriz sim

**Comment by caahreginaa** [comment]
Eu acho muito boa a ideia da matriz tbm

**Comment by wesleysilas** [comment]
Matriz sim... ate pq salvaria a transiçao!

**Comment by eilins** [comment]
E salvando a transição na matriz, já mostraria pro usuário que aquele espaço já está ocupado.

**Comment by caahreginaa** [comment]
Já que a ideia já foi implementada, encerrarei aqui.
