### ISSUE TITLE
Entrada de dados

### ISSUE THREAD

**Issue by caahreginaa** [RafaelRSPX/AllPetri#6]
Pessoal, adicionei uma nova milestone para amanhã e a missão é que terminemos toda a parte de entrada de dados do usuário.

**Comment by wesleysilas** [comment]
ok... gogo

**Comment by RafaelRSPX** [comment]
Fazendo a parte da transição

**Comment by flavioduart** [comment]
Conseguiremos!

**Comment by RafaelRSPX** [comment]
Acredito que esteja tudo certo?

**Comment by flavioduart** [comment]
Acredito que a entrada de dados já esteja quase toda pronta

**Comment by eilins** [comment]
Também acho que já esteja ok!

**Comment by caahreginaa** [comment]
Vou só adicionar uma restrição para que não haja uma transição de um local para o mesmo local e aí esta encerrada a parte da entrada de dados.

**Comment by RafaelRSPX** [comment]
Restrição para transição para o mesmo lugar implementado: b28666bff00cc88ec47e0094ca0f906183d56df1
