### ISSUE TITLE
Necessário por limite de tokens em cada lugar?

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/AllPetri#7]
Estou com dúvida se seria necessário por um certo limite de tokens nos lugares.

**Comment by caahreginaa** [comment]
Acho que seria válido um limite de 100 tokens

**Comment by RafaelRSPX** [comment]
Se todo concordarem, alguém implementa esse limite.

**Comment by flavioduart** [comment]
Eu concordo

**Comment by caahreginaa** [comment]
Implementei o máximo de tokens,
