### ISSUE TITLE
Limite de transições?

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/AllPetri#8]
Aproveitando a dúvida sobre o limite de tokens, vocês acham necessário por algum limite de transições?

**Comment by flavioduart** [comment]
Eu acho que transição não teria limite não, o que poderia fazer era botar que o número de transição não poderia ser maior que o número de lugares

**Comment by caahreginaa** [comment]
Mas é claro que o número de transição pode ser maior que o número de lugares....

**Comment by caahreginaa** [comment]
Se for ter um limite e eu acho que TALVEZ seja válido, 500 ou 1000 estaria bom.

**Comment by RafaelRSPX** [comment]
Então não é necessário por limite?

**Comment by caahreginaa** [comment]
Não acho necessário por limite não

**Comment by flavioduart** [comment]
Concordo com Cassia, acho melhor não limitar.

**Comment by RafaelRSPX** [comment]
Então fechado.
