### ISSUE TITLE
Processamento

### ISSUE THREAD

**Issue by caahreginaa** [RafaelRSPX/AllPetri#9]
Companheiros, pensando já na parte do processamento de dados, já poderíamos começar a implementar a parte do código que ira contar 60 segundos para que seja encerrado o processamento.

**Comment by RafaelRSPX** [comment]
Isso. Como o professor falou, vai ser necessário a biblioteca time.h para fazer a comparação do horário da máquina

**Comment by flavioduart** [comment]
:+1: :ok:

**Comment by eilins** [comment]
Exatamente, temos que pegar a hora atual e a hora que começou a rodar o programa, pra contar 60sgs :dancer:

**Comment by caahreginaa** [comment]
Pessoal, estamos com problemas. A função de processamento não esta recebendo corretamente os valores da struct que possui as variaveis que precisamos. Acredito que teremos que usar ponteiros.

**Comment by RafaelRSPX** [comment]
Acredito que resolve no commit: 94e02a1b029099a42898b4b868ce1629ad632bb6

**Comment by caahreginaa** [comment]
Resolveu sim, muito boa Rafael!

**Comment by caahreginaa** [comment]
Processamento completo!
